version: '2' 

services: 
  db:
    build: build
    container_name: tdsc_db
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hybris
      MYSQL_DATABASE: tdsc-db
      MYSQL_PASSWORD: hybris
    volumes:
      - /data/db/data:/var/lib/mysql
      - /data/db/conf:/etc/mysql/conf.d/source
      - /data/dump:/docker-entrypoint-initdb.d

